name: Waka Github Action

on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: "0 */1 * * *"

jobs:
  update-readme:
    name: Updates WakaTime statistics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
